### PR TITLE
add OEL supprt

### PR DESCRIPTION
**Pull request by sjoeboo**
add support for OEL 5 (facter reports operating system as OEL)

### CODE REVIEW

**Comment by trlinkin** [comment]
Hey, thanks for the addition. You can verify that OEL 5 has the same defaults as the other EL based systems? Just checking.

**Comment by trlinkin** [comment]
Also, if you confirm, I'll merge. Your PR failed testing because of a problem of mine that I've fixed I believe. Turns out a decent amount changed in Rspec 3.

**Comment by sjoeboo** [comment]
Yeah, I can verify the defaults are identical, I've had my fork of this in prod. for ~2 weeks now.

**Comment by trlinkin** [comment]
Release coming soon!

**Comment by trlinkin** [comment]
BTW, release 1.1.0 is on the forge

**Pull request merged**
